name: Build CSS

on:
  push:
    branches:
      - main
    paths:
      - 'assets/css/*.css'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Build CSS
      run: yarn

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Yarn builder
        author_email: nik.samoylov@campaignforaisafety.org
        message: 'Built CSS'
        add: '*'        
